services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Tourze\CmsSearchBundle\Controller\:
    resource: '../../Controller/'
  Tourze\CmsSearchBundle\Repository\:
    resource: '../../Repository/'
  Tourze\CmsSearchBundle\Service\:
    resource: '../../Service/'
    public: true
